### ISSUE TITLE
Trouble importing Stilr via require()

### ISSUE THREAD

**Issue by doctyper** [kodyl/stilr#15]
Not sure if this is a Stilr bug or a transpiler bug, but as of `1.2.0` I cannot `require` Stilr via:

```js
var StyleSheet = require("Stilr");
```

Instead I have to work-around the default export:

```js
var StyleSheet = require("Stilr").default;
```

**Comment by chriskjaer** [comment]
Ohh, seems like there's some clash between the new `import` and the good old commonjs `require` and the tests didn't catch it because I'm using es6 with imports. 

Tests have been added for this and it should be fixed in `1.2.1`.
