### ISSUE TITLE
v1.2.2 not working on internet explorer

### ISSUE THREAD

**Issue by louiscloutierdakis** [kodyl/stilr#33]
Currently in version 1.2.2,  dist/util.js Number.isInteger is used as is.

It should be used with babel, so it output something like var _Number$isInteger = require('babel-runtime/core-js/number/is-integer')['default'];

Currently, it's failing on internet explorer because of that.

**Comment by danieljuhl** [comment]
What happens, if you include babel-runtime in your project? Does it solve the problem?

Nonetheless, I'll have a look tomorrow and publish a new version, built with babel-runtime.

**Comment by danieljuhl** [comment]
Babel-runtime should be included, and is now, as of v1.2.4

**Comment by louiscloutierdakis** [comment]
@danieljuhl Thanks you, it's working now on internet explorer with v1.2.4
