### ISSUE TITLE
Error: Cannot find module 'react/lib/CSSPropertyOperations'

### ISSUE THREAD

**Issue by SpainTrain** [kodyl/stilr#37]
`CSSPropertyOperations` has moved from the `react` package to the `react-dom` package.

**Comment by dano-giftbit** [comment]
[#38](https://github.com/kodyl/stilr/pull/38) should address this issue.

**Comment by danieljuhl** [comment]
Thanks! I'll make a release tonight or tomorrow morning.

**Comment by dano-giftbit** [comment]
@danieljuhl  Thanks, this is the last dependency that's breaking our build so I'm keen to get it fixed.

**Comment by danieljuhl** [comment]
Yes, and it is breaking a few of ours :) So rest assured, that this will be fixed/released first thing tomorrow morning.

**Comment by danieljuhl** [comment]
This has been fixed in `1.2.5`, as `stilr` no longer depends on `react`
