### ISSUE TITLE
Code in NPM isn't compiled

### ISSUE THREAD

**Issue by KyleAMathews** [kodyl/stilr#8]

**Comment by KyleAMathews** [comment]
I take that back. The code is compiled but it's expecting Map(s) etc. to be available. Not a Babel expert but it needs https://babeljs.io/docs/usage/runtime/#core-js-aliasing enabled?

**Comment by chriskjaer** [comment]
Yeah, it uses Map internally. Corejs might be the right way to go if we can limit it to only polyfilling Map when needed (I'm not a babel expert either)
